module.exports = {
  'prefix': '.',
  'bot_name': 'Vitek',
  'bot_author': 'Mihaszki',
  'status': '.help / .info',
  'github_link': 'https://github.com/Mihaszki/vitek-discord-bot',
  'date_timezone': 'Europe/Warsaw',
  'date_locale': 'pl-PL',
  'excludeRegex': /^\.|^!|^\+|^-|^=|(https:\/\/|http:\/\/|www\.)/im,
  'swearWordList': 'sra|fiut|skurw|cipa|cipy|cipe|cipo|cipk|pener|kurw|huj|spierd|wypierd|odpierd|cwel|gown|dupa|dupe|dupo|dupk|japa|jape|pizda|pizde|pizdy|pizdo|pedal|morda|morde|franca|frajer|mordy|szcza|rucha|debil|ciec|szmata|szmato|szmaty|szmate|kupa|kupe|kutas|jeban|jebal|dziwk|ujeb|odjeb|zajeb|wyjeb|zjeb|jeb|leszcz|suki|suka|bitch|fuck|shit|ass|cunt|slut|bastard|dick|retard|idiot',
  'positiveRepMessages': [
    'Good job!', 'That\'s what I\'m talking about!', 'Thanks for the ride!', 'Thanks for that, tough guy!', 'All right, I feel good.', 'Thanks, doc.', 'Aw, fellas!', 'Un-freakin\'-touchable!', 'Woooooo!', 'Yeah! We did it!', 'You were good son, real good, maybe even the best.', 'Godspeed, you magnificent bastard.', 'Oktoberfest!', 'Today is a good day.', 'Outstanding!', 'And that is how you do it, men!', 'Mmph mphna mprh.', 'We did it, mate!', 'Cheers, mate!', 'I had me good eye on you the whole time!', 'Aye, that\'s the way ye do it!', 'Guts and glory, lads!', 'Bloody brilliant!', 'That\'s the spirit!', 'I am hero!', 'Who dares stand against me NOW?', 'I am credit to team.', 'Sandvich make me strong!', 'Makin\' bacon!', 'Nice goin\', pardner!', 'Thanks, mister!', 'Another satisfied customer!', 'Thanks for the ride, pardner!', 'Unicorn, erecting a dispenser!', 'Danke, Kamerad!', 'Ve did it, Kamerad!', 'Danke, mein hard-hatted friend!', 'I am fully charged.', 'I am ze Übermensch!', 'No worries!', 'God Save the Queen!', 'Preciate it.', 'Excellent.', 'Top Shelf!', 'Well played.', 'Gentlemen?', 'Thank you, laborer!', 'Cheers!', 'My pleasure.', 'You\'re a champion!', 'Good stuff!',
  ],
  'negativeRepMessages': [
    'Bruh...', 'Take your little gun and get out of my trailer park!', 'You cheeseburger walrus!', 'You onion ring sasquatch!', 'You mustard tiger!', 'Bonk!', 'Say goodbye to ya kneecaps, chucklehead!', 'You got owned!', 'What is your major malfunction, brother?', 'Take that, ya dumb, bib-wearin\' dope!', 'Disguise dat!', 'Don\'t you ever cross me again!', 'This is a real frickin\' embarrassment.', 'Maggots!', 'This is my world. You are not welcome in my world.', 'Got anything funny to say about that, funny man?', 'Dominated, hippie, get a job!', 'Get a haircut, hippie.', 'I will send my condolences to your kangaroo wife.', 'Oh, they\'re goin\' ta have to glue you back together...IN HELL!', 'Let that be a bloody lesson to yeh!', 'Welcome to the Dominatening!', 'Keep crying, baby!', 'Never, never, make me angry.', 'Don\'t run! It\'s just ham!', 'This thing ain\'t on auto-pilot, son!', 'Gotcha, chuckwagon!', 'You just ain\'t doin\' it right.', 'Let\'s do this Texas style.', 'Can you feel ze Schadenfreude?', 'Auf Wiedersehen, Schweinehunds!', 'You bloody pikers!', 'You big head wankers!', 'Piss off, big-head!', 'This is getting too easy, mate.', 'Dom-in-ated, ya little ankle-biter!', 'Dominated, ya ploddin\' potatohead!', 'Take that, ya quack!', 'Peek-a-boo!', 'Burn in hell, you mumbling abomination!', 'Oh, please, just stay down!', 'Ugh...merde.', 'Bomb has been planted.', 'Easy peasy, lemon squeezy!',
  ],
  'loveQuotes': [
    'You know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.', 'The best thing to hold onto in life is each other.', 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'I swear I couldn\'t love you more than I do right now, and yet I know I will tomorrow.', 'When I saw you I fell in love, and you smiled because you knew it.', 'Remember, we\'re madly in love, so it\'s all right to kiss me any time you feel like it.', 'I love you not because of who you are, but because of who I am when I am with you.', 'As long as the sun continues to shine, you can be sure that my heart will remain yours.', 'Whenever you\'re having a bad day, remember this: I LOVE YOU.', 'If love was a storybook we\'d meet on the very first page.', 'One word frees us of all the weight and pain of life: that word is love.', 'To be your friend was all I ever wanted; to be your lover was all I ever dreamed.', 'I love you more than coffee, but please don\'t make me prove it.', 'I believe there are some things in life you can\'t deny or rationalize, and love is one of them.', 'There is a madness in loving you, a lack of reason that makes it feel so flawless.', 'You are the last thought in my mind before I drift off to sleep and the first thought when I wake up each morning.', 'I will love you until the stars go out, and the tides no longer turn.',
  ],
  'poemTitles': [
    'The Red @', 'The @ Land', 'The @ Not Taken', 'There Will Come Soft @', 'If You Forget @', 'Thirteen Ways of Looking at a @', 'Do Not Go Gentle into That Good @', 'We Wear the @', 'Meditations in @', 'Diving into the @', 'The @ Poem', 'The Golden @',
  ],
};